DROP table if exists arti_article;
create table arti_article (
   id bigint generated by default as identity, 
   content clob, 
   create_time timestamp, 
   process_instance_id varchar(255), 
   title varchar(255), 
   user_id bigint, 
   primary key (id));

DROP table if exists arti_process_log;
create table arti_process_log (
       id bigint generated by default as identity, 
       content varchar(255), 
       result varchar(255), 
       task_id varchar(255), 
       task_name varchar(255), 
       user_id varchar(255), 
       article_id bigint,
       primary key (id));
       
DROP table if exists dynamic_script;
create table dynamic_script (
       id bigint generated by default as identity, 
       dynamic_script_type varchar(20), 
       last_updated timestamp, 
       script_name varchar(50), 
       script_source clob, 
       primary key (id));

DROP table if exists sec_config;
create table sec_config (
       id bigint generated by default as identity, 
       config_name varchar(20) unique NOT NULL, 
       name varchar(20) NOT NULL, 
       config_type varchar(2) NOT NULL, 
       value varchar(50) NOT NULL, 
       description varchar(255), 
       primary key (id));
 
DROP table if exists sec_group;
create table sec_group (
      id bigint generated by default as identity, 
      name varchar(50) unique NOT NULL, 
      parent_id bigint, 
      primary key (id));

DROP table if exists sec_resource;
create table sec_resource (
       id bigint generated by default as identity, 
       name varchar(20) unique NOT NULL, 
       permission varchar(50), 
       resource_type varchar(2) NOT NULL, 
       url varchar(255), 
       parent_id bigint, 
       primary key (id));
 
DROP table if exists sec_role;
create table sec_role (
      id bigint generated by default as identity, 
      role_name varchar(20) unique NOT NULL, 
      name varchar(20) NOT NULL, 
      status varchar(2) NOT NULL, 
      primary key (id));

DROP table if exists sec_role_resource;
create table sec_role_resource (
       role_id bigint not null, 
       resource_id bigint not null, 
       primary key (role_id, resource_id));

DROP table if exists sec_user;
create table sec_user (
       id bigint generated by default as identity, 
       login_name varchar(20) unique NOT NULL, 
       name varchar(20) NOT NULL, 
       password varchar(50) NOT NULL, 
       salt varchar(50), 
       sex varchar(2) NOT NULL, 
       email varchar(255), 
       status varchar(2) NOT NULL, 
       group_id bigint, primary key (id));

DROP table if exists sec_user_role;
create table sec_user_role (
       user_id bigint not null, 
       role_id bigint not null, 
       primary key (user_id, role_id));
       
       
alter table arti_process_log add constraint FK_ARTICLE_ID foreign key (article_id) references arti_article;

alter table sec_group add constraint FK_GROUP_ID foreign key (parent_id) references sec_group;

alter table sec_resource add constraint FK_RESOURCE_ID foreign key (parent_id) references sec_resource;

alter table sec_role_resource add constraint FK_ROLE_RESOURCE_RESOURCE_ID foreign key (resource_id) references sec_resource;

alter table sec_role_resource add constraint FK_ROLE_RESOURCE_ROLE_ID foreign key (role_id) references sec_role;

alter table sec_user add constraint FK_USER_GROUP_ID foreign key (group_id) references sec_group;

alter table sec_user_role add constraint FK_USER_ROLE_ROLE_ID foreign key (role_id) references sec_role;

alter table sec_user_role add constraint FK_USER_ROLE_USER_ID foreign key (user_id) references sec_user;